server:
  port: 8485

management:
  security:
    enabled: ${MANAGEMENT_SECURITY_ENABLED:true}

idam:
  s2s-auth:
    url: ${S2S_URL}

spring:
  application:
    name: Send Letter Provider
  datasource:
      url: jdbc:postgresql://${LETTER_TRACKING_DB_HOST:send-letter-database}:${LETTER_TRACKING_DB_PORT:5432}/${LETTER_TRACKING_DB_NAME:letter_tracking}${LETTER_TRACKING_DB_CONN_OPTIONS:}
      username: ${LETTER_TRACKING_DB_USER_NAME:letterservice}
      password: ${LETTER_TRACKING_DB_PASSWORD:}
      properties:
        charSet: UTF-8
      tomcat:
        max-active: 10
        max-idle: 10
        min-idle: 2
        max-wait: 10000
        test-on-borrow: true
        test-on-connect: true
        test-on-idle: true
        validation-query: "SELECT 1"
        time-between-eviction-runs-millis: 10000
        test-while-idle: true
        test-on-return: true
        remove-abandoned: true
        # Allow connections 2 hours idle before timing out.
        remove-abandoned-timeout: 7200
        log-abandoned: true
        abandon-when-percentage-full: 0

  jackson:
    serialization:
      write_dates_as_timestamps: false

ftp:
  hostname: ${FTP_HOSTNAME}
  port: ${FTP_PORT}
  target-folder: ${FTP_TARGET_FOLDER}
  smoke-test-target-folder: ${FTP_SMOKE_TEST_TARGET_FOLDER:SMOKE_TEST}
  reports-folder: ${FTP_REPORTS_FOLDER}
  reports-cron: ${FTP_REPORTS_CRON:0 30 0 * * *}
  fingerprint: ${FTP_FINGERPRINT}
  username: ${FTP_USER}
  privateKey: ${FTP_PRIVATE_KEY}
  publicKey: ${FTP_PUBLIC_KEY}
  downtime:
    from: ${FTP_DOWNTIME_FROM:16:00}
    to: ${FTP_DOWNTIME_TO:17:00}

scheduling.enabled: ${SCHEDULING_ENABLED:false}

tasks:
  upload-letters-interval-ms: ${UPLOAD_LETTERS_INTERVAL:30000}
  mark-letters-posted: ${FTP_REPORTS_CRON:0 30 0 * * *}
  stale-letters-report: ${STALE_LETTERS_REPORT_CRON:0 30 1 * * *}

encryption:
  enabled: ${ENCRYPTION_ENABLED:false}
  publicKey: ${ENCRYPTION_PUBLIC_KEY}

